#
# Module manifest for module 'ColorScripts-Enhanced'
#
# Generated by: Nick2bad4u
#
# Generated on: 10/26/2025
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'ColorScripts-Enhanced.psm1'

    # Version number of this module.
    ModuleVersion = '2025.10.26.1957'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID = 'f77548d7-23eb-48ce-a6e0-f64b4758d995'

    # Author of this module
    Author = 'Nick2bad4u'

    # Company or vendor of this module
    CompanyName = 'Community'

    # Copyright statement for this module
    Copyright = '(c) 2025. All rights reserved.'

    # Description of the functionality provided by this module
    Description = @'
Enhanced PowerShell ColorScripts with high-performance caching system. Display beautiful ANSI art in your terminal with 6-19x faster load times.

Features:
• 498 beautiful colorscripts - Extensive collection of ANSI art
• Intelligent Caching - 6-19x performance improvement (5-20ms load times)
• OS-Wide Cache - Consistent caching across all terminal sessions
• Simple API - Easy-to-use cmdlets with tab completion
• Configurable Defaults - Persist cache locations and startup behaviour
• Auto-Update - Cache automatically invalidates when scripts change
• Centralized Storage - Cache stored in AppData/ColorScripts-Enhanced/cache
• Cross-platform - Works on Windows, Linux, and macOS
• PowerShell 5.1+ and PowerShell Core 7+ compatible

Quick Start: Show-ColorScript (or alias: scs)
Full documentation: https://github.com/Nick2bad4u/ps-color-scripts-enhanced
'@

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    ProcessorArchitecture = 'None'

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Show-ColorScript'
        'Get-ColorScriptList'
        'Build-ColorScriptCache'
        'Clear-ColorScriptCache'
        'Add-ColorScriptProfile'
        'Get-ColorScriptConfiguration'
        'Set-ColorScriptConfiguration'
        'Reset-ColorScriptConfiguration'
        'Export-ColorScriptMetadata'
        'New-ColorScript'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @('scs')

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    FileList = @(
        'ColorScripts-Enhanced.psm1'
        'ColorScripts-Enhanced.psd1'
        'README.md'
        'README-Gallery.md'
        'ScriptMetadata.psd1'
        'Install.ps1'
    )

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @(
                'ColorScripts'
                'ANSI'
                'Terminal'
                'Art'
                'Cache'
                'Performance'
                'PowerShell'
                'Startup'
                'Terminal-Startup'
                'ANSI-Art'
                'Colorful-Terminal'
                'PowerShell-Art'
                'Fancy-Terminal'
                'Terminal-Enhancement'
                'Beautiful-Terminal'
                'Terminal-Colors'
                'PowerShell-Scripts'
                'Terminal-Art'
                'Colorful-Scripts'
                'Enhanced-Terminal'
                'Terminal-Visuals'
                'PowerShell-Module'
                'Colorful-Output'
                'Terminal-Themes'
                'PSEdition_Desktop'
                'PSEdition_Core'
                'Windows'
                'Linux'
                'MacOS'
            )

            # A URL to the license for this module.
            LicenseUri = 'https://licenses.nuget.org/MIT'

            # License expression or path to license file
            License = 'MIT'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Nick2bad4u/ps-color-scripts-enhanced'

            # A URL to an icon representing this module.
            IconUri = 'https://raw.githubusercontent.com/Nick2bad4u/ps-color-scripts-enhanced/main/docs/colorscripts-icon.png'

            # ReleaseNotes of this module
            ReleaseNotes = @'
Version 2025.10.26.1957:
- Enhanced caching system with OS-wide cache in AppData
- 6-19x performance improvement
- Cache stored in centralized location
- Works from any directory
- 498 beautiful colorscripts included
- Full comment-based help documentation
- Scripts optimized for performance and visual quality
- Cross-platform support (Windows, Linux, macOS)
- PowerShell 5.1+ and PowerShell Core 7+ compatible
'@

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()
        }
    }

    # HelpInfo URI of this module
    HelpInfoURI = 'https://nick2bad4u.github.io/PS-Color-Scripts-Enhanced/ColorScripts-Enhanced/'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}
