#
# Module manifest for module 'ColorScripts-Enhanced'
#
# Generated by: Nick
#
# Generated on: 10/9/2025
#

@{

    RootModule           = 'ColorScripts-Enhanced.psm1'
    ModuleVersion        = '2025.10.9.1633'
    CompatiblePSEditions = @('Desktop', 'Core')
    GUID                 = 'f77548d7-23eb-48ce-a6e0-f64b4758d995'
    Author               = 'Nick'
    CompanyName          = 'Community'
    Copyright            = '(c) 2025. All rights reserved.'
    Description          = 'Enhanced PowerShell ColorScripts with high-performance caching system. Display beautiful ANSI art in your terminal with 6-19x faster load times.'
    PowerShellVersion    = '5.1'

    FunctionsToExport    = @(
        'Show-ColorScript'
        'Get-ColorScriptList'
        'Build-ColorScriptCache'
        'Clear-ColorScriptCache'
        'Add-ColorScriptProfile'
    )

    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @('scs')

    PrivateData          = @{

        PSData = @{
            Tags         = @(
                'ColorScripts'
                'ANSI'
                'Terminal'
                'Art'
                'Cache'
                'Performance'
                'PowerShell'
                'Startup'
                'Terminal Startup'
                'ANSI Art'
                'Colorful Terminal'
                'PowerShell Art'
            )

            LicenseUri   = 'https://github.com/Nick2bad4u/ps-color-scripts-enhanced/blob/main/LICENSE'
            ProjectUri   = 'https://github.com/Nick2bad4u/ps-color-scripts-enhanced'

            ReleaseNotes = @'
Version 2025.10.09.1633:
- Added Add-ColorScriptProfile helper for one-line profile integration
- Installer updated with -SkipStartupScript and helper reuse
- New Lint-Module.ps1 and CI linting treat warnings as errors
- Documentation refreshed for gallery-first installation and tooling guidance
'@
        }
    }

    HelpInfoURI          = 'https://github.com/Nick2bad4u/ps-color-scripts-enhanced/tree/main/ColorScripts-Enhanced/en-US'
}
