name: Publish PowerShell Module

on:
    push:
        branches:
            - main

jobs:
    publish-to-gallery:
        runs-on: ubuntu-latest
        steps:
            - name: Set Timezone
              run: sudo timedatectl set-timezone America/Detroit

            - uses: actions/checkout@v4
            - name: Build and publish
              env:
                  NUGET_KEY: ${{ secrets.NUGET_KEY }}
              shell: pwsh
              run: |
                  ./build.ps1
                  Publish-Module -Path ./ps-color-scripts-enhanced/ColorScripts-Enhanced -NuGetApiKey $env:NUGET_KEY -Verbose
