name: Publish PowerShell Module

on:
    push:
        branches:
            - main

jobs:
    publish-to-gallery:
        runs-on: ubuntu-latest
        steps:
            - name: Set Timezone
              run: sudo timedatectl set-timezone America/Detroit

            - uses: actions/checkout@v5
            - name: Build and publish
              env:
                  NUGET_KEY: ${{ secrets.NUGET_KEY }}
                  PSGalleryApiKey: ${{ secrets.PSGalleryApiKey }}
              shell: pwsh
              run: |
                  Publish-Module -Path ./ColorScripts-Enhanced -NuGetApiKey $env:NUGET_KEY -Verbose
                  Publish-Module -Path ./ColorScripts-Enhanced -NuGetApiKey $env:PSGalleryApiKey -Verbose -Repository PSGallery
